# Site settings
title: Xinddy
email: xinddy@126.com
description: 我的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xinddy.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
